In [1]:
import pandas as pd

from imblearn.over_sampling import RandomOverSampler, SMOTE, ADASYN, BorderlineSMOTE, SMOTENC
from imblearn.under_sampling import RandomUnderSampler, TomekLinks, NearMiss, ClusterCentroids, EditedNearestNeighbours

import pandas as pd 
import numpy as np


from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.feature_selection import SelectFromModel, SequentialFeatureSelector
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import f1_score,accuracy_score,recall_score,precision_score,confusion_matrix,roc_auc_score

import warnings
warnings.simplefilter('ignore')

In [2]:
def model_basic(x_train, y_train, x_test, y_test): 
    models = [
        LogisticRegression(),
        LinearDiscriminantAnalysis(),
        GaussianNB(),
        RandomForestClassifier(),
        XGBClassifier()
    ]

    rdict={'model':[],'acc_train':[], 'auc_train':[], 'acc_test':[],'precision':[],'recall':[],'f1_score':[], 'AUC_test':[]}


    for clf in models:
        clf = clf.fit(x_train, y_train)
    #1열:Train
        y_hat = clf.predict(x_train)
        results_train  = (round(accuracy_score(y_train,y_hat),2),round(roc_auc_score(y_train,y_hat),2))
    #2열:Test
        y_hat = clf.predict(x_test)
        results = (round(accuracy_score(y_test,y_hat),2),
                        round(precision_score(y_test,y_hat),2),
                        round(recall_score(y_test,y_hat),2),
                        round(f1_score(y_test,y_hat),2),
                        round(roc_auc_score(y_test,y_hat),2))

        rdict['model'].append(clf); 
        rdict['acc_train'].append(results_train[0])
        rdict['auc_train'].append(results_train[1])
        
        rdict['acc_test'].append(results[0])
        rdict['precision'].append(results[1])
        rdict['recall'].append(results[2])
        rdict['f1_score'].append(results[3])
        rdict['AUC_test'].append(results[4])   

        confusion = confusion_matrix(y_test, y_hat)

        print(confusion)

    rdf_final = pd.DataFrame(data=rdict)
    return rdf_final

In [3]:
# def model_basic(x_train, y_train, x_test, y_test):
#     models = [
#         LogisticRegression(),
#         LinearDiscriminantAnalysis(),
#         GaussianNB(),
#         RandomForestClassifier(),
#         XGBClassifier(),
        
#     ]

#     rdict = {'model': [], 'accuracy': [], 'precision': [], 'recall': [], 'f1_score': [], 'auc_score': []}

#     for clf in models:
#         clf = clf.fit(x_train, y_train)
#         pred = clf.predict(x_test)
#         pred_prob_rf = clf.predict_proba(x_test)[:, 1].reshape(-1, 1)
#         auc_score = roc_auc_score(y_test, pred_prob_rf)
#         results = (
#             round(accuracy_score(y_test, pred), 4),
#             round(precision_score(y_test, pred), 4),
#             round(recall_score(y_test, pred), 4),
#             round(f1_score(y_test, pred), 4),
#             round(auc_score, 4)
#         )

#         rdict['model'].append(clf)
#         rdict['accuracy'].append(results[0])
#         rdict['precision'].append(results[1])
#         rdict['recall'].append(results[2])
#         rdict['f1_score'].append(results[3])
#         rdict['auc_score'].append(results[4])

#         confusion = confusion_matrix(y_test, pred)
#         print(confusion)

#     rdf = pd.DataFrame(data=rdict)
#     return rdf

In [4]:
def over(df, target, method='random', sampling_strategy=1.0):
    
    # 타겟 변수와 특성 변수를 분리
    X = df
    y = target
    
    if method == 'random':
        # RandomOverSampler 객체 생성, sampling_strategy 값 설정
        oversampler = RandomOverSampler(sampling_strategy=sampling_strategy)

    elif method == 'smote':
        # SMOTE 객체 생성, sampling_strategy 값 설정
        oversampler = SMOTE(sampling_strategy=sampling_strategy)

    elif method == 'adasyn':
        # adasyn 객체 생성, sampling_strategy 값 설정
        oversampler = ADASYN(sampling_strategy=sampling_strategy)

    elif method == 'Borderline-SMOTE':
        # Borderline-SMOTE 객체 생성, sampling_strategy 값 설정
        oversampler = BorderlineSMOTE(sampling_strategy=sampling_strategy)

    elif method == 'SMOTENC':
        # SMOTENC 객체 생성, sampling_strategy 값 설정
        oversampler = SMOTENC(sampling_strategy=sampling_strategy)

    
    # 오버샘플링 수행
    X_resampled, y_resampled = oversampler.fit_resample(X, y)

    # 오버샘플링된 데이터 프레임 생성
    df_over = pd.concat([X_resampled, y_resampled], axis=1)

    return df_over


In [5]:
def under(df, target, method='random', sampling_strategy=1.0):
    
    # 타겟 변수와 특성 변수를 분리
    X = df
    y = target

    if method == 'random':
        # RandomUnderSampler 객체 생성, sampling_strategy 값 설정
        undersampler = RandomUnderSampler(sampling_strategy=sampling_strategy)

    elif method == 'tomek':
        # TomekLinks 객체 생성, sampling_strategy 값 설정
        undersampler = TomekLinks(sampling_strategy=sampling_strategy)

    elif method == 'NearMiss':
        # NearMiss 객체 생성, sampling_strategy 값 설정
        undersampler = NearMiss(sampling_strategy=sampling_strategy)

    elif method == 'cluster_centroids':
        # ClusterCentroids 객체 생성, sampling_strategy 값 설정
        undersampler = ClusterCentroids(sampling_strategy=sampling_strategy)

    elif method == 'edited_nn':
        # EditedNearestNeighbours 객체 생성, sampling_strategy 값 설정
        undersampler = EditedNearestNeighbours(sampling_strategy=sampling_strategy)

    # 언더샘플링 수행
    X_resampled, y_resampled = undersampler.fit_resample(X, y)

    # 언더샘플링된 데이터 프레임 생성
    df_under = pd.concat([X_resampled, y_resampled], axis=1)

    return df_under

In [6]:
def evaluate_resampling_model(x_train, y_train, x_test, y_test, method, num_iterations=10, over_ratio = 0.5 ,under_ratio=0.5,random_state=None):
    

    # 모델 성능 저장을 위한 리스트
    score = {"accuracy_scores_mean" : [] ,"f1_scores_mean" :[], "recall_scores_mean" : [] , "precision_scores_mean" : [],  "auc_mean" : []}
    std_score = {"accuracy_scores_std" : [] ,"f1_scores_std" :[], "recall_scores_std" : [] , "precision_scores_std" : [],  "auc_std" : []}  

    recall_scores=[]
    accuracy_scores=[]
    f1_scores=[]
    precision_scores=[]
    auc_scores=[]
    
    
    # 랜덤샘플러 생성
    sampler_over = BorderlineSMOTE(sampling_strategy=over_ratio, random_state=random_state)
    sampler_under = RandomUnderSampler(sampling_strategy=under_ratio, random_state=random_state)

    

    # 랜덤 샘플링 반복 수행
    for i in range(num_iterations):
        
        x_train_over, y_train_over = sampler_over.fit_resample(x_train, y_train)
        x_test_under, y_test_under = sampler_under.fit_resample(x_test, y_test)

        if method == "Logistic":
            model = LogisticRegression().fit(x_train_over, y_train_over)
            y_pred = model.predict(x_test_under)
            y_pred_proba = model.predict_proba(x_test_under)[:,1].reshape(-1,1)

        if method == "LDA":
            model = LinearDiscriminantAnalysis().fit(x_train_over, y_train_over)
            y_pred = model.predict(x_test_under)
            y_pred_proba = model.predict_proba(x_test_under)[:,1].reshape(-1,1)
        
        if method == "Gaussian":
            model = GaussianNB().fit(x_train_over, y_train_over)
            y_pred = model.predict(x_test_under)
            y_pred_proba = model.predict_proba(x_test_under)[:,1].reshape(-1,1)
        
        #모델 성능 평가 
        accuracy = accuracy_score(y_test_under, y_pred)
        f1 = f1_score(y_test_under, y_pred)
        recall = recall_score(y_test_under, y_pred)
        precision = precision_score(y_test_under, y_pred)
        auc = roc_auc_score(y_test_under, y_pred_proba)
        
        # 리스트에 결과값 담아주기
        accuracy_scores.append(accuracy)
        f1_scores.append(f1)
        recall_scores.append(recall)
        precision_scores.append(precision)
        auc_scores.append(auc)

    

    # 모델 성능 평균 및 표준편차 계산
    accuracy_mean = np.mean(accuracy_scores)
    f1_mean = np.mean(f1_scores)
    recall_mean = np.mean(recall_scores)
    precision_mean = np.mean(precision_scores)
    auc_scores_mean = np.mean(auc_scores)


    score["accuracy_scores_mean"].append(accuracy_mean)
    score["f1_scores_mean"].append(f1_mean)
    score["recall_scores_mean"].append(recall_mean)
    score["precision_scores_mean"].append(precision_mean)
    score["auc_mean"].append(auc_scores_mean)

    accuracy_std = np.std(accuracy_scores)
    f1_std = np.std(f1_scores)
    recall_std = np.std(recall_scores)
    precision_std = np.std(precision_scores)
    auc_scores_std = np.std(auc_scores)

    std_score["accuracy_scores_std"].append(accuracy_std)
    std_score["f1_scores_std"].append(f1_std)
    std_score["recall_scores_std"].append(recall_std)
    std_score["precision_scores_std"].append(precision_std)
    std_score["auc_std"].append(auc_scores_std)
    
    print(score)
    print(std_score)

---
# target1

In [7]:
train = pd.read_csv("./datasets/통계검증완료/코스피_standard_train.csv", index_col=0)
test = pd.read_csv("./datasets/통계검증완료/코스피_standard_test.csv", index_col=0)


최종_col_1=['누적수익성비율', 'EBITDA마진율', 'TMD', '금융비용부담률', '자기자본순이익률']


x_train = train[최종_col_1]
y_train = train["target_1"]

x_test = test[최종_col_1]
y_test = test["target_1"]




In [8]:
y_train.value_counts()

0.0    3388
1.0      50
Name: target_1, dtype: int64

In [9]:
y_test.value_counts()

0.0    2014
1.0       9
Name: target_1, dtype: int64

In [10]:
## 불균형 처리 안한 적합
model_basic(x_train, y_train, x_test, y_test)

[[1970   44]
 [   6    3]]
[[1972   42]
 [   6    3]]
[[1866  148]
 [   3    6]]
[[1955   59]
 [   5    4]]
[[1972   42]
 [   6    3]]


model  acc_train  auc_train  \
0                               LogisticRegression()       0.99       0.85   
1                       LinearDiscriminantAnalysis()       0.99       0.84   
2                                       GaussianNB()       0.97       0.92   
3  (DecisionTreeClassifier(max_features='sqrt', r...       1.00       1.00   
4  XGBClassifier(base_score=None, booster=None, c...       1.00       1.00   

   acc_test  precision  recall  f1_score  AUC_test  
0      0.98       0.06    0.33      0.11      0.66  
1      0.98       0.07    0.33      0.11      0.66  
2      0.93       0.04    0.67      0.07      0.80  
3      0.97       0.06    0.44      0.11      0.71  
4      0.98       0.07    0.33      0.11      0.66

In [11]:
## train 데이터만 1:2 오버샘플링후 적합

train_1 =over(train[최종_col_1],train["target_1"], method='Borderline-SMOTE', sampling_strategy=0.5)

model_basic(train_1[최종_col_1], train_1["target_1"], x_test, y_test)

[[1863  151]
 [   1    8]]
[[1905  109]
 [   2    7]]
[[1791  223]
 [   1    8]]
[[1949   65]
 [   1    8]]
[[1939   75]
 [   3    6]]


model  acc_train  auc_train  \
0                               LogisticRegression()       0.95       0.94   
1                       LinearDiscriminantAnalysis()       0.94       0.92   
2                                       GaussianNB()       0.93       0.92   
3  (DecisionTreeClassifier(max_features='sqrt', r...       1.00       1.00   
4  XGBClassifier(base_score=None, booster=None, c...       1.00       1.00   

   acc_test  precision  recall  f1_score  AUC_test  
0      0.92       0.05    0.89      0.10      0.91  
1      0.95       0.06    0.78      0.11      0.86  
2      0.89       0.03    0.89      0.07      0.89  
3      0.97       0.11    0.89      0.20      0.93  
4      0.96       0.07    0.67      0.13      0.81

In [12]:
## train 데이터 오버 1:0.5, test 데이터 언더 1:0.5 

train_1 =over(train[최종_col_1],train["target_1"], method='Borderline-SMOTE', sampling_strategy=0.5)

test_1 =under(test[최종_col_1],test["target_1"], method='random', sampling_strategy=0.5)

model_basic(train_1[최종_col_1], train_1["target_1"], test_1[최종_col_1], test_1["target_1"])


[[17  1]
 [ 1  8]]
[[18  0]
 [ 2  7]]
[[17  1]
 [ 1  8]]
[[18  0]
 [ 1  8]]
[[18  0]
 [ 2  7]]


model  acc_train  auc_train  \
0                               LogisticRegression()       0.95       0.94   
1                       LinearDiscriminantAnalysis()       0.94       0.92   
2                                       GaussianNB()       0.93       0.92   
3  (DecisionTreeClassifier(max_features='sqrt', r...       1.00       1.00   
4  XGBClassifier(base_score=None, booster=None, c...       1.00       1.00   

   acc_test  precision  recall  f1_score  AUC_test  
0      0.93       0.89    0.89      0.89      0.92  
1      0.93       1.00    0.78      0.88      0.89  
2      0.93       0.89    0.89      0.89      0.92  
3      0.96       1.00    0.89      0.94      0.94  
4      0.93       1.00    0.78      0.88      0.89

In [13]:
# 반복샘플링
evaluate_resampling_model(x_train, y_train,x_test,y_test,
                          method='Logistic',over_ratio=0.5,under_ratio=0.5,num_iterations=1000)

{'accuracy_scores_mean': [0.9145925925925926], 'f1_scores_mean': [0.8767908849081553], 'recall_scores_mean': [0.8888888888888892], 'precision_scores_mean': [0.8700329670329672], 'auc_mean': [0.9676203703703704]}
{'accuracy_scores_std': [0.03867425780458176], 'f1_scores_std': [0.048524537319240814], 'recall_scores_std': [3.3306690738754696e-16], 'precision_scores_std': [0.09331053215131133], 'auc_std': [0.029566212837435633]}


In [14]:
evaluate_resampling_model(x_train, y_train,x_test,y_test,
                          method='LDA',over_ratio=0.5,under_ratio=0.5,num_iterations=1000)

{'accuracy_scores_mean': [0.8916296296296295], 'f1_scores_mean': [0.8296792053663571], 'recall_scores_mean': [0.777777777777778], 'precision_scores_mean': [0.895164393939394], 'auc_mean': [0.9661728395061727]}
{'accuracy_scores_std': [0.03565041358842928], 'f1_scores_std': [0.044944023465886655], 'recall_scores_std': [2.220446049250313e-16], 'precision_scores_std': [0.09975321067736266], 'auc_std': [0.032005503165726465]}


--- 
# targer2

In [16]:
train = pd.read_csv("./datasets/통계검증완료/코스피_standard_train.csv", index_col=0)
test = pd.read_csv("./datasets/통계검증완료/코스피_standard_test.csv", index_col=0)


최종_col_2= ['총자본정상영업이익률', '누적수익성비율', 'EBITDA마진율', 'TMD', '금융비용부담률', '자기자본순이익률',
       '총자본증가율']

x_train = train[최종_col_2]
y_train = train["target_2"]

x_test = test[최종_col_2]
y_test = test["target_2"]



In [17]:
## 불균형 처리 안한 적합
model_basic(x_train, y_train, x_test, y_test)

[[1986   31]
 [   4    2]]
[[1980   37]
 [   4    2]]
[[1854  163]
 [   1    5]]
[[1977   40]
 [   4    2]]
[[1997   20]
 [   4    2]]


model  acc_train  auc_train  \
0                               LogisticRegression()       0.99       0.82   
1                       LinearDiscriminantAnalysis()       0.99       0.84   
2                                       GaussianNB()       0.98       0.91   
3  (DecisionTreeClassifier(max_features='sqrt', r...       1.00       1.00   
4  XGBClassifier(base_score=None, booster=None, c...       1.00       1.00   

   acc_test  precision  recall  f1_score  AUC_test  
0      0.98       0.06    0.33      0.10      0.66  
1      0.98       0.05    0.33      0.09      0.66  
2      0.92       0.03    0.83      0.06      0.88  
3      0.98       0.05    0.33      0.08      0.66  
4      0.99       0.09    0.33      0.14      0.66

In [18]:
## train 데이터만 1:2 오버샘플링후 적합

train_1 =over(train[최종_col_2],train["target_2"], method='Borderline-SMOTE', sampling_strategy=0.5)

model_basic(train_1[최종_col_2], train_1["target_2"], x_test, y_test)

[[1923   94]
 [   0    6]]
[[1939   78]
 [   0    6]]
[[1840  177]
 [   0    6]]
[[1997   20]
 [   3    3]]
[[1989   28]
 [   2    4]]


model  acc_train  auc_train  \
0                               LogisticRegression()       0.98       0.98   
1                       LinearDiscriminantAnalysis()       0.97       0.97   
2                                       GaussianNB()       0.97       0.97   
3  (DecisionTreeClassifier(max_features='sqrt', r...       1.00       1.00   
4  XGBClassifier(base_score=None, booster=None, c...       1.00       1.00   

   acc_test  precision  recall  f1_score  AUC_test  
0      0.95       0.06    1.00      0.11      0.98  
1      0.96       0.07    1.00      0.13      0.98  
2      0.91       0.03    1.00      0.06      0.96  
3      0.99       0.13    0.50      0.21      0.75  
4      0.99       0.12    0.67      0.21      0.83

In [19]:
## train 데이터 오버 1:0.5, test 데이터 언더 1:0.5 

train_1 =over(train[최종_col_2],train["target_2"], method='Borderline-SMOTE', sampling_strategy=0.5)

test_1 =under(test[최종_col_2],test["target_2"], method='random', sampling_strategy=0.5)

model_basic(train_1[최종_col_2], train_1["target_2"], test_1[최종_col_2], test_1["target_2"])

[[12  0]
 [ 0  6]]
[[12  0]
 [ 0  6]]
[[12  0]
 [ 0  6]]
[[12  0]
 [ 3  3]]
[[12  0]
 [ 2  4]]


model  acc_train  auc_train  \
0                               LogisticRegression()       0.98       0.98   
1                       LinearDiscriminantAnalysis()       0.97       0.97   
2                                       GaussianNB()       0.97       0.97   
3  (DecisionTreeClassifier(max_features='sqrt', r...       1.00       1.00   
4  XGBClassifier(base_score=None, booster=None, c...       1.00       1.00   

   acc_test  precision  recall  f1_score  AUC_test  
0      1.00        1.0    1.00      1.00      1.00  
1      1.00        1.0    1.00      1.00      1.00  
2      1.00        1.0    1.00      1.00      1.00  
3      0.83        1.0    0.50      0.67      0.75  
4      0.89        1.0    0.67      0.80      0.83

In [20]:
evaluate_resampling_model(x_train, y_train,x_test,y_test,
                          method='Logistic',over_ratio=0.5,under_ratio=0.5,num_iterations=1000)

{'accuracy_scores_mean': [0.9688333333333333], 'f1_scores_mean': [0.9585467032967033], 'recall_scores_mean': [1.0], 'precision_scores_mean': [0.9252404761904763], 'auc_mean': [0.9800694444444444]}
{'accuracy_scores_std': [0.04188015676742624], 'f1_scores_std': [0.053611979510172506], 'recall_scores_std': [0.0], 'precision_scores_std': [0.09430043773328597], 'auc_std': [0.031074429640286817]}


In [21]:
evaluate_resampling_model(x_train, y_train,x_test,y_test,
                          method='LDA',over_ratio=0.5,under_ratio=0.5,num_iterations=1000)

{'accuracy_scores_mean': [0.9718333333333333], 'f1_scores_mean': [0.9609762237762238], 'recall_scores_mean': [0.9903333333333334], 'precision_scores_mean': [0.9378095238095239], 'auc_mean': [0.9800069444444445]}
{'accuracy_scores_std': [0.03659719850304946], 'f1_scores_std': [0.04993455620003356], 'recall_scores_std': [0.038957241517677633], 'precision_scores_std': [0.08320894117314837], 'auc_std': [0.03029908064932738]}


----
# target3 


In [22]:
test.columns

Index(['회사명', '거래소코드', '회계년도', '산업군', 'target_1', 'target_2', 'target_3',
       '현금흐름/총부채비율', '총자본정상영업이익률', '현금흐름 대 자산', 'EBIT/총자산', '타인자본회전률',
       '당기전기영업손익', '이익잉여금', '총자본회전률', '차입금의존도', '누적수익성비율', 'EBITDA마진율',
       '순운전자본비율', 'TMD', '금융비용부담률', '자기자본순이익률', '부채비율', '외국인지분율', 'ROA변화율',
       '총자본증가율', '매출액총이익률', '매출액증가율', '영업현금흐름-단기차입금', '자본금회전률', '정상영업이익증가율',
       '대주주지분율'],
      dtype='object')

In [7]:
train = pd.read_csv("./datasets/통계검증완료/코스피_standard_train.csv", index_col=0)
test = pd.read_csv("./datasets/통계검증완료/코스피_standard_test.csv", index_col=0)

최종_col_3= ['총자본정상영업이익률', '누적수익성비율', 'EBITDA마진율', 'TMD', '금융비용부담률', '자기자본순이익률',
       '총자본증가율']


x_train = train[최종_col_3]
y_train = train["target_3"]

x_test = test[최종_col_3]
y_test = test["target_3"]



In [8]:
## 불균형 처리 안한 적합
model_basic(x_train, y_train, x_test, y_test)

[[1986   31]
 [   4    2]]
[[1980   37]
 [   4    2]]
[[1854  163]
 [   1    5]]
[[1974   43]
 [   4    2]]
[[1997   20]
 [   4    2]]


model  acc_train  auc_train  \
0                               LogisticRegression()       0.99       0.82   
1                       LinearDiscriminantAnalysis()       0.99       0.84   
2                                       GaussianNB()       0.98       0.91   
3  (DecisionTreeClassifier(max_features='sqrt', r...       1.00       1.00   
4  XGBClassifier(base_score=None, booster=None, c...       1.00       1.00   

   acc_test  precision  recall  f1_score  AUC_test  
0      0.98       0.06    0.33      0.10      0.66  
1      0.98       0.05    0.33      0.09      0.66  
2      0.92       0.03    0.83      0.06      0.88  
3      0.98       0.04    0.33      0.08      0.66  
4      0.99       0.09    0.33      0.14      0.66

In [9]:
## train 데이터만 1:2 오버샘플링후 적합

train_1 =over(train[최종_col_3],train["target_3"], method='Borderline-SMOTE', sampling_strategy=0.5)

model_basic(train_1[최종_col_3], train_1["target_3"], x_test, y_test)

[[1919   98]
 [   0    6]]
[[1936   81]
 [   0    6]]
[[1837  180]
 [   0    6]]
[[1995   22]
 [   3    3]]
[[1991   26]
 [   3    3]]


model  acc_train  auc_train  \
0                               LogisticRegression()       0.98       0.98   
1                       LinearDiscriminantAnalysis()       0.97       0.96   
2                                       GaussianNB()       0.97       0.97   
3  (DecisionTreeClassifier(max_features='sqrt', r...       1.00       1.00   
4  XGBClassifier(base_score=None, booster=None, c...       1.00       1.00   

   acc_test  precision  recall  f1_score  AUC_test  
0      0.95       0.06     1.0      0.11      0.98  
1      0.96       0.07     1.0      0.13      0.98  
2      0.91       0.03     1.0      0.06      0.96  
3      0.99       0.12     0.5      0.19      0.74  
4      0.99       0.10     0.5      0.17      0.74

In [10]:
## train 데이터 오버 1:0.5, test 데이터 언더 1:0.5 

train_1 =over(train[최종_col_3],train["target_3"], method='Borderline-SMOTE', sampling_strategy=0.5)

test_1 =under(test[최종_col_3],test["target_3"], method='random', sampling_strategy=0.5)

model_basic(train_1[최종_col_3], train_1["target_3"], test_1[최종_col_3], test_1["target_3"])


[[12  0]
 [ 0  6]]
[[12  0]
 [ 0  6]]
[[12  0]
 [ 0  6]]
[[12  0]
 [ 3  3]]
[[12  0]
 [ 2  4]]


model  acc_train  auc_train  \
0                               LogisticRegression()       0.98       0.98   
1                       LinearDiscriminantAnalysis()       0.97       0.97   
2                                       GaussianNB()       0.97       0.97   
3  (DecisionTreeClassifier(max_features='sqrt', r...       1.00       1.00   
4  XGBClassifier(base_score=None, booster=None, c...       1.00       1.00   

   acc_test  precision  recall  f1_score  AUC_test  
0      1.00        1.0    1.00      1.00      1.00  
1      1.00        1.0    1.00      1.00      1.00  
2      1.00        1.0    1.00      1.00      1.00  
3      0.83        1.0    0.50      0.67      0.75  
4      0.89        1.0    0.67      0.80      0.83

In [27]:
evaluate_resampling_model(x_train, y_train,x_test,y_test,
                          method='Logistic',over_ratio=0.5,under_ratio=0.5,num_iterations=1000)

{'accuracy_scores_mean': [0.969], 'f1_scores_mean': [0.9585065934065935], 'recall_scores_mean': [1.0], 'precision_scores_mean': [0.9248428571428572], 'auc_mean': [0.9811875]}
{'accuracy_scores_std': [0.03985451939302974], 'f1_scores_std': [0.05159523126359475], 'recall_scores_std': [0.0], 'precision_scores_std': [0.09142936643999591], 'auc_std': [0.02967344046548432]}


In [28]:
evaluate_resampling_model(x_train, y_train,x_test,y_test,
                          method='LDA',over_ratio=0.5,under_ratio=0.5,num_iterations=1000)

{'accuracy_scores_mean': [0.9706666666666668], 'f1_scores_mean': [0.9596825008325008], 'recall_scores_mean': [0.9886666666666667], 'precision_scores_mean': [0.9373916666666666], 'auc_mean': [0.9801319444444443]}
{'accuracy_scores_std': [0.04094621585192695], 'f1_scores_std': [0.05489869519960657], 'recall_scores_std': [0.0419576506068255], 'precision_scores_std': [0.08913405945057323], 'auc_std': [0.03235073674314194]}


----
## target1 - 정상:부실 = 1:0.5    - boderine_smote 했을때 성능이 가장 좋음 


In [11]:
id_col = ['회사명', '거래소코드', '회계년도', '산업군','target_3']
가져가는_col = id_col + 최종_col_3 
train_1.to_csv('./datasets/불균형처리/boder_코스피_standard_train.csv',encoding='utf-8-sig')
test[가져가는_col].to_csv('./datasets/불균형처리/코스피_standard_test.csv',encoding='utf-8-sig')